### ISSUE TITLE
Create an NX workspace

### ISSUE THREAD

**Issue by naimulcsx** [naimulcsx/progHours#191]
#192  

**Tasks**
- [x] Create Nx Workspace
- [x] Generate client - React /w Vite
  - [x] Setup React Router
  - [x] Setup Mantine
  - [x] Setup Axios and Storage (lib)
  - [x] Setup TanStack Query v4
  - [x] Add Dockerfile and captain-definition
  - [x] Add captain build script
- [x] Generate API - NestJS
  - [x] Setup global ValidationPipe
  - [x] Setup Config Module
- [x] Update prettier config
- [x] Setup Husky & Commitlint
