### ISSUE TITLE
Setup NestJS API.

### ISSUE THREAD

**Issue by naimulcsx** [naimulcsx/progHours#194]
**Tasks**

- [x] Add docker-compose.yml
- [x] Setup Prisma
- [x] Setup database module
- [x] Add auth module
  - [x] POST /auth/signin
  - [x] POST /auth/signup
- [x] Add Role Based Access Control (RBAC)
- [x] Add API Docs for authentication
- [x] Enable API Versioning
- [x] Secure HTTP headers with Helmet
- [x] Add users module
  - [x] GET /users
  - [x] POST /users
  - [x] GET /users/me
  - [x] GET /users/{username}
  - [x] PATCH /users/{username}
- [x] Add OJ problem parsers library
